name: Rust

on:
  push:
  pull_request:
  
env:
  SHELL: /bin/bash
  CXX: clang++
  CC: clang

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install autoconf2.13 gcc-7 g++-7 ccache llvm clang lld -y
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          default: true
    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-${{ hashFiles('**/COMMIT') }}
    - name: Build POSIX
      run: |
        ccache -z
        cd mozjs
        cd js
        cd src
        autoconf2.13
        cd ..
        cd ..
        cd ..
        make || exit 0
        ccache -s
